name: Deploy
on:
  push:
    branches: production
  pull_request:
    branches: production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "deno-minesweeper"
          entrypoint: "./main.ts"
          import-map: import_map.json
